afterInstall: yarn turbo build

nodeLinker: node-modules

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js"
  - checksum: 00959c0d2a5826bc669416a83428f711bbd22a02aa6534f07749b3d806ab35b9d66352f0c967fbd2b4e03cdadc31193af7dd403dd359c1a897d97ff60a358adc
    path: .yarn/plugins/correct-yarn-formatting.cjs
    spec: "https://raw.githubusercontent.com/HanseltimeIndustries/correct-yarn-formatting/v1.0.2/lib/index.js"
