name: iOS E2E Tests

inputs:
  app_name:
    description: 'Name of the app to test'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        clean: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Install Metro dependencies
      working-directory: external/metro
      run: yarn set version 1.22.22 && yarn install
      shell: bash

    - name: Cache Pods
      uses: actions/cache@v3
      with:
        path: apps/${{ inputs.app_name }}/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('apps/${{ inputs.app_name }}/ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install Pods
      run: yarn pods
      working-directory: apps/${{ inputs.app_name }}
      shell: bash

    - name: Install Maestro CLI and iOS Utilities
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        brew tap facebook/fb
        brew install facebook/fb/idb-companion
        echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      shell: bash

    - uses: callstackincubator/ios@v1
      with:
        github-token: ${{ inputs.github_token }}
        destination: 'simulator'
        scheme: 'MFExampleHost'
        configuration: 'Release'
        working-directory: './apps/example-host'

    - name: Shutdown all iOS simulators
      shell: bash
      run: |
        xcrun simctl shutdown all

    - name: Run iOS E2E Tests
      run: |
        yarn workspace ${{ inputs.app_name }} e2e:prepare:ios &
        yarn workspace ${{ inputs.app_name }} ios:release
        yarn workspace ${{ inputs.app_name }} e2e:run
      shell: bash

    - name: Upload Maestro Logs on Failure
      if: failure() # Runs only if any of the previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: maestro-logs-ios-${{ inputs.app_name }}
        path: ~/.maestro/tests/

