name: Trigger E2E Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-matrix-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        app_name: [example-host]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android E2E Tests
        uses: ./.github/actions/android-e2e
        with:
          app_name: ${{ matrix.app_name }}
  e2e-matrix-ios:
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        app_name: [example-host]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: iOS E2E Tests
        uses: ./.github/actions/ios-e2e
        with:
          app_name: ${{ matrix.app_name }}
